# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180405_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
    ]
